### ISSUE TITLE
_tkinter.TclError: expected integer but got "%#"

### ISSUE THREAD

**Issue by Moosems** [rdbende/tkinterDnD#6] opened 2023-05-06 15:45 UTC
```pythonfrom tkinterDnD import Tk
root = Tk()
root.register_drop_target("*")
root.bind("<<Drop>>", print)
root.mainloop()
```

After dragging a file onto the window, I got this:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1947, in __call__
    args = self.subst(*args)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1632, in _substitute
    e.serial = getint(nsign)
               ^^^^^^^^^^^^^
_tkinter.TclError: expected integer but got "%#"
```

**Comment by rdbende** [comment] 2023-05-06 15:47
Duplicate of #4

**Closed as not planned** 2023-05-06 15:47 UTC
